name: veg
channels:
  - conda-forge
dependencies:
  - gdal==3.6.2
  - ipympl==0.9.3
  - ipywidgets==7.7.3
  - matplotlib==3.6.3
  - numpy==1.24.2
  - opensarlab_lib==0.0.8 
  - pandas==1.5.3
  - pip==23.0.1
  - scikit-image==0.19.3
  - pip:
      - awscli==1.27.79
